# 1.Print 'Hello HCIA'.

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a,b=1,3
c=a+b
print (c)

4


# 3.Define a list and replicate in three different ways.

In [3]:
listone=['A','B','C']
print(listone)
print(listone[:])
listone

['A', 'B', 'C']
['A', 'B', 'C']


['A', 'B', 'C']

In [4]:
type(listone)

list

# 4.Define two lists and merge them together.

In [5]:
listone=[1,3,5,7]
listtwo=[2,4,6,8]
mergelist=listone+listtwo
print(mergelist)

[1, 3, 5, 7, 2, 4, 6, 8]


# 5. Get the last element of the list and print it.

In [6]:
listone=['A','B','C']
listone[-1]

'C'

# 6.Define a tuple that contains only one element.

In [7]:
tupleone=('A',)
print(tupleone)

('A',)


In [8]:
type(tupleone)

tuple

# 7.Define a three-line long string.

In [9]:
print('''My
name is
Kate''')

My
name is
Kate


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [10]:
a=(1,2,3)
print(a)

(1, 2, 3)


In [11]:
type(a)

tuple

In [12]:
for i in a:
    print(i)

1
2
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [13]:
def Mul(a, b):
    return a*b
Mul(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [14]:
import numpy as np
a=np.zeros([5, 5], dtype = int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [15]:
import numpy as np
b=np.zeros([4, 6], dtype = int)
b

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [16]:
import numpy as np
c = np.arange(15).reshape(3, 5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [17]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[5,6,7], [8,9,10], [11,12,13]])
result = a.dot(b)
result

array([[ 54,  60,  66],
       [126, 141, 156]])